services:
  webapiexample:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 11000:11000

  webapiexampledb:
    ports:
      - 5440:5432
